### ISSUE TITLE
Update for paper : Image Compression for Machine and Human Vision with Spatial-Frequency Adaptation

### ISSUE THREAD

**Issue by qingshi9974** [Kobaayyy/Awesome-ECCV2024-ECCV2020-Low-Level-Vision#2]
arixv: http://arxiv.org/abs/2407.09853

Thanks for your contribution!

**Comment by Kobaayyy** [comment]
> arixv: http://arxiv.org/abs/2407.09853
> 
> Thanks for your contribution!

Thanks, I've added it.
