### ISSUE TITLE
Update for paper : SMFANet: A Lightweight Self-Modulation Feature Aggregation Network for Efficient Image Super-Resolution

### ISSUE THREAD

**Issue by Zheng-MJ** [Kobaayyy/Awesome-ECCV2024-ECCV2020-Low-Level-Vision#3]
Thanks for your contribution!
The paper “SMFANet: A Lightweight Self-Modulation Feature Aggregation Network for Efficient Image Super-Resolution” now is available.
The paper link: https://github.com/Zheng-MJ/SMFANet/blob/main/assets/SMFANet.pdf

**Comment by Kobaayyy** [comment]
> Thanks for your contribution! The paper “SMFANet: A Lightweight Self-Modulation Feature Aggregation Network for Efficient Image Super-Resolution” now is available. The paper link: https://github.com/Zheng-MJ/SMFANet/blob/main/assets/SMFANet.pdf

Thanks, I've added it.
